[workspace]
members = [ "client","server", "types"]
resolver = "2"

[workspace.dependencies]
serde = { version = "1.0.197", features = ["derive"] }
thiserror = "1.0.58"
candid = "0.10.6"
log = "0.4.21"
yral-identity = { git = "https://github.com/go-bazzinga/yral-identity.git", default-features = false, rev = "6ed9acfd9d98a16db457ea1e2ebf2ba76626c426" }
