# fly.toml app configuration file generated for yral-metadata on 2024-03-29T18:25:06+05:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'yral-metadata'
primary_region = 'sin'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[services.concurrency]
  hard_limit = 10000
  soft_limit = 50


[[vm]]
  memory = '16gb'
  cpu_kind = 'performance'
  cpus = 8
