version: '3.8'

services:
  yral-metadata:
    image: ${APP_IMAGE:-ghcr.io/dolr-ai/yral-metadata}:${IMAGE_TAG:-latest}
    container_name: yral-metadata
    restart: unless-stopped
    ports:
      - "7000:7000"
    environment:
      - BIND_ADDRESS=0.0.0.0:7000 
      - JWT_PUBLIC_KEY=${JWT_PUBLIC_KEY}
      - YRAL_METADATA_USER_NOTIFICATION_API_KEY=${YRAL_METADATA_USER_NOTIFICATION_API_KEY}
      - CLIENT_NOTIFICATIONS_GOOGLE_SERVICE_ACCOUNT_KEY=${CLIENT_NOTIFICATIONS_GOOGLE_SERVICE_ACCOUNT_KEY}
      - GOOGLE_CLIENT_NOTIFICATIONS_PROJECT_ID=${GOOGLE_CLIENT_NOTIFICATIONS_PROJECT_ID}
      - BACKEND_ADMIN_IDENTITY=${BACKEND_ADMIN_IDENTITY}
      - YRAL_AUTH_PUBLIC_KEY=${YRAL_AUTH_PUBLIC_KEY}
      - GOOGLE_CLIENT_NOTIFICATIONS_SENDER_ID=${GOOGLE_CLIENT_NOTIFICATIONS_SENDER_ID}
      - QSTASH_CURRENT_SIGNING_KEY=${QSTASH_CURRENT_SIGNING_KEY}
      - QSTASH_NEXT_SIGNING_KEY=${QSTASH_NEXT_SIGNING_KEY}
      - DRAGONFLY_REDIS_STORE_PASSWORD=${DRAGONFLY_REDIS_STORE_PASSWORD}
      - DRAGONFLY_REDIS_STORE_HOSTS=${DRAGONFLY_REDIS_STORE_HOSTS}
      - DRAGONFLY_REDIS_STORE_CA_CERT=${DRAGONFLY_REDIS_STORE_CA_CERT}
      - DRAGONFLY_REDIS_STORE_CLIENT_CERT=${DRAGONFLY_REDIS_STORE_CLIENT_CERT}
      - DRAGONFLY_REDIS_STORE_CLIENT_KEY=${DRAGONFLY_REDIS_STORE_CLIENT_KEY}
    networks:
      - proxy
        
networks:
  proxy:
  external: true
