name: Add Pull Request to project
# This workflow runs whenever a pull request in the repository is marked as "ready for review".
on:
  pull_request:
    types:
      - ready_for_review
      
jobs:
  add_pr:
    runs-on: ubuntu-latest
    steps:
    # Uses the [actions/create-github-app-token](https://github.com/marketplace/actions/create-github-app-token) action to generate an installation access token for your app from the app ID and private key. The installation access token is accessed later in the workflow as `${{ steps.generate-token.outputs.token }}`.
    #
    # Replace `APP_ID` with the name of the configuration variable that contains your app ID.
    #
    # Replace `APP_PEM` with the name of the secret that contains your app private key.
      - name: Generate token
        id: generate-token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ vars.PROJECT_WORKFLOW_APP_ID }}
          private-key: ${{ secrets.PROJECT_WORKFLOW_APP_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}

      - name: Add pull request to project
        uses: actions/add-to-project@v1.0.2
        with:
          project-url: https://github.com/orgs/dolr-ai/projects/12
          github-token: ${{ steps.generate-token.outputs.token }}
          


          
