name: deploy preview
on:
  pull_request:
    types: [opened, reopened, synchronize, closed]

permissions:
  deployments: write

env:
  FLY_API_TOKEN: ${{ secrets.AUTH_METADATA_MICROSERVICE_FLY_IO_GITHUB_ACTION }}
  FLY_ORG: gobazzinga-inc-584

jobs:
  build_check:
    uses: ./.github/workflows/build.yml
    with:
      publish-artifact: true

  preview:
    needs: build_check
    runs-on: ubuntu-latest

    # Only run one deployment at a time per PR.
    concurrency:
      group: pr-${{ github.event.number }}

    # Create a GitHub deployment environment per staging app so it shows up
    # in the pull request UI.
    environment:
      name: pr-${{ github.event.number }}
      url: ${{ steps.deploy.outputs.url }}

    steps:
      - uses: actions/checkout@v3
      - name: Download build
        uses: actions/download-artifact@v4
        with:
          name: build-musl
      - run: chmod +x target/x86_64-unknown-linux-musl/release/yral-metadata-server

      - name: Deploy
        id: deploy
        uses: superfly/fly-pr-review-apps@1.2.1

      - uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Set secret tokens
        if: ${{ github.event.pull_request.merged == false}}
        run: |
          APP_NAME="pr-${{github.event.number}}-yral-dapp-yral-metadata"
          flyctl secrets set REDIS_URL=$REDIS_URL --app "$APP_NAME" --stage
          flyctl secrets set JWT_PUBLIC_KEY="$JWT_PUBLIC_KEY" --app "$APP_NAME" --stage
        env:
          REDIS_URL: ${{ secrets.AUTH_FLY_IO_UPSTASH_REDIS_DATABASE_CONNECTION_STRING }}
          FLY_API_TOKEN: ${{ secrets.AUTH_METADATA_MICROSERVICE_FLY_IO_GITHUB_ACTION }}
          JWT_PUBLIC_KEY: ${{ secrets.YRAL_AUTH_METADATA_SERVICE_ACCESS_PUBLIC_KEY }}
