name: Upload secrets to vault

on:
  workflow_dispatch:
  push:
    branches:
      - naitik/coolify-and-vault-integration

permissions:
  id-token: write   
  contents: read

jobs:
  upload-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Authenticate to Vault
        uses: hashicorp/vault-action@v3
        with:
          url: https://vault.yral.com
          method: jwt
          role: yral-metadata-write-role
          jwtGithubAudience: "https://github.com/dolr-ai"
          exportToken: true
      
      - name: Install Vault CLI
        run: |
          wget -O- https://apt.releases.hashicorp.com/gpg | sudo gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg
          echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list
          sudo apt update && sudo apt install vault

      - name: Set Secrets
        env:
          VAULT_ADDR: https://vault.yral.com
          YRAL_AUTH_METADATA_SERVICE_ACCESS_PUBLIC_KEY: ${{ secrets.YRAL_AUTH_METADATA_SERVICE_ACCESS_PUBLIC_KEY }}
          YRAL_APP_ADMIN_AND_PROPOSAL_SUBMITTER_DFX_IDENTITY_SECP_PRIVATE_KEY: ${{ secrets.YRAL_APP_ADMIN_AND_PROPOSAL_SUBMITTER_DFX_IDENTITY_SECP_PRIVATE_KEY }}
          YRAL_AUTH_JWT_VERIFY_PUBLIC_KEY: ${{ secrets.YRAL_AUTH_JWT_VERIFY_PUBLIC_KEY }}
        run: |
          vault kv put secret/yral-metadata/YRAL_AUTH_METADATA_SERVICE_ACCESS_PUBLIC_KEY value="$YRAL_AUTH_METADATA_SERVICE_ACCESS_PUBLIC_KEY"
          vault kv put secret/yral-metadata/YRAL_APP_ADMIN_AND_PROPOSAL_SUBMITTER_DFX_IDENTITY_SECP_PRIVATE_KEY value="$YRAL_APP_ADMIN_AND_PROPOSAL_SUBMITTER_DFX_IDENTITY_SECP_PRIVATE_KEY"
          vault kv put secret/yral-metadata/YRAL_AUTH_JWT_VERIFY_PUBLIC_KEY value="$YRAL_AUTH_JWT_VERIFY_PUBLIC_KEY"