name: Upload secrets to vault

on:
  workflow_dispatch:

permissions:
  id-token: write   
  contents: read

jobs:
  upload-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Authenticate to Vault
        uses: hashicorp/vault-action@v3
        with:
          url: https://vault.yral.com
          method: jwt
          role: yral-metadata-write-role
          jwtGithubAudience: "https://github.com/dolr-ai"
          exportToken: true
      
      - name: Install Vault CLI
        run: |
          wget -O- https://apt.releases.hashicorp.com/gpg | sudo gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg
          echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list
          sudo apt update && sudo apt install vault

      - name: Set Secrets
        env:
          VAULT_ADDR: https://vault.yral.com
          JWT_PUBLIC_KEY: ${{ secrets.YRAL_AUTH_METADATA_SERVICE_ACCESS_PUBLIC_KEY }}
          YRAL_METADATA_USER_NOTIFICATION_API_KEY: ${{ secrets.YRAL_METADATA_USER_NOTIFICATION_API_KEY }}
          CLIENT_NOTIFICATIONS_GOOGLE_SERVICE_ACCOUNT_KEY: ${{ secrets.CLIENT_NOTIFICATIONS_GOOGLE_SERVICE_ACCOUNT_KEY }}
          GOOGLE_CLIENT_NOTIFICATIONS_PROJECT_ID: ${{ vars.GOOGLE_CLIENT_NOTIFICATIONS_PROJECT_ID }}
          BACKEND_ADMIN_IDENTITY: ${{ secrets.YRAL_APP_ADMIN_AND_PROPOSAL_SUBMITTER_DFX_IDENTITY_SECP_PRIVATE_KEY }}
          YRAL_AUTH_PUBLIC_KEY: ${{ secrets.YRAL_AUTH_JWT_VERIFY_PUBLIC_KEY }}
          GOOGLE_CLIENT_NOTIFICATIONS_SENDER_ID: ${{ vars.GOOGLE_CLIENT_NOTIFICATIONS_SENDER_ID }}
          QSTASH_CURRENT_SIGNING_KEY: ${{ secrets.QSTASH_CURRENT_SIGNING_KEY }}
          QSTASH_NEXT_SIGNING_KEY: ${{ secrets.QSTASH_NEXT_SIGNING_KEY }}
          DRAGONFLY_PASSWORD: ${{ secrets.DRAGONFLY_PASSWORD }}
          DRAGONFLY_HOSTS: ${{ vars.DRAGONFLY_HOSTS }}
          DRAGONFLY_CA_CERT: ${{ secrets.DRAGONFLY_CA_CERT }}
          DRAGONFLY_CLIENT_CERT: ${{ secrets.DRAGONFLY_CLIENT_CERT }}
          DRAGONFLY_CLIENT_KEY: ${{ secrets.DRAGONFLY_CLIENT_KEY }}        
        run: |
          vault kv put secret/yral-metadata/JWT_PUBLIC_KEY value="$JWT_PUBLIC_KEY" \
          vault kv put secret/yral-metadata/YRAL_METADATA_USER_NOTIFICATION_API_KEY value="$YRAL_METADATA_USER_NOTIFICATION_API_KEY" \
          vault kv put secret/yral-metadata/CLIENT_NOTIFICATIONS_GOOGLE_SERVICE_ACCOUNT_KEY value="$CLIENT_NOTIFICATIONS_GOOGLE_SERVICE_ACCOUNT_KEY" \
          vault kv put secret/yral-metadata/GOOGLE_CLIENT_NOTIFICATIONS_PROJECT_ID value="$GOOGLE_CLIENT_NOTIFICATIONS_PROJECT_ID" \
          vault kv put secret/yral-metadata/BACKEND_ADMIN_IDENTITY value="$BACKEND_ADMIN_IDENTITY" \
          vault kv put secret/yral-metadata/YRAL_AUTH_PUBLIC_KEY value="$YRAL_AUTH_PUBLIC_KEY" \
          vault kv put secret/yral-metadata/GOOGLE_CLIENT_NOTIFICATIONS_SENDER_ID value="$GOOGLE_CLIENT_NOTIFICATIONS_SENDER_ID" \
          vault kv put secret/yral-metadata/QSTASH_CURRENT_SIGNING_KEY value="$QSTASH_CURRENT_SIGNING_KEY" \
          vault kv put secret/yral-metadata/QSTASH_NEXT_SIGNING_KEY value="$QSTASH_NEXT_SIGNING_KEY" \
          vault kv put secret/yral-metadata/DRAGONFLY_PASSWORD value="$DRAGONFLY_PASSWORD" \
          vault kv put secret/yral-metadata/DRAGONFLY_HOSTS value="$DRAGONFLY_HOSTS" \
          vault kv put secret/yral-metadata/DRAGONFLY_CA_CERT value="$DRAGONFLY_CA_CERT" \
          vault kv put secret/yral-metadata/DRAGONFLY_CLIENT_CERT value="$DRAGONFLY_CLIENT_CERT" \
          vault kv put secret/yral-metadata/DRAGONFLY_CLIENT_KEY value="$DRAGONFLY_CLIENT_KEY"